name: 'Create GitHub Repository'
description: 'A custom GitHub Action to create a new GitHub repository'
inputs:
  repo-name:
    description: 'The name of the repository to create'
    required: true
  repo-description:
    description: 'A description for the new repository'
    required: false
    default: ''
  github-token:
    description: 'A token to create the new repository'
    required: true
runs:
  using: 'node12'
  main: 'index.js'