name: Create Repository Workflow

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the new repository'
        required: true
        default: 'test-token'
      repo_description:
        description: 'Description of the new repository'
        required: false
      private:
        description: 'Set repository to private'
        required: true
        default: 'true'
        
jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create new repository
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/fernandaakl \
          -d '{
            "name": "${{ github.event.inputs.repo_name }}",
            "description": "${{ github.event.inputs.repo_description }}",
            "private": ${{ github.event.inputs.private }}
          }'
